# Generated by Django 3.2 on 2022-06-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('link', models.URLField(max_length=250)),
                ('project_image', models.ImageField(upload_to='projects/')),
            ],
        ),
    ]
